### ISSUE TITLE
[Redfish] Framework of redfish support

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat2-task-management#156]
* [x] framework of perl part
* [ ] framework for all commands "get" type option (python)
* [ ] Simple testcase for testing whether get new information

**Comment by xuweibj** [comment]
Close it, will open new task for redfish support.
