### ISSUE TITLE
[Feature] Secure root supporting during provision

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat2-task-management#173]
Till now,  xCAT stateful (kickstart) and stateless (image) provision will include the root password hash inside, and those are exposed to a HTTP server.  Here might be security issue.

To enforce more security consideration, it is required to offer a capability to send the root password hash in secure method during the provisioning.

This EPIC should cover below tasks:
* [x] [Mini design for the solution](#174 ) (https://github.com/xcat2/xcat-core/wiki/Secure-root-support)
* [x]  As an admin, he can set an option in `site` to enable the capability, and the root password can only be set via secure method during the provision. And the kickstart file and image will not contains the root passwd hash.
~~* [ ]  As an admin, he can set a temp password using during provisioning (Optional)~~
* [x]  FVT for Secure root supporting feature including test cases. (Working...)
* [x]  Update document.

~~Note:  only for RHEL7 first.~~  From the code investigation, it seems it should work for all platform.

If using shadow file in synclist, then password in table `passwd` is the temporary installation password, no more helpful to set a new one.

**Comment by zet809** [comment]
The story is done, let's close it.
