### ISSUE TITLE
Support Ubuntu 18.04

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat2-task-management#194]
* [x]  Can support with workarounds
* [ ] Issues for Ubuntu 18.04 should be fixed
* [ ] RTD documents verification, modify the document if needed

**Comment by zet809** [comment]
The phase 1 of the 18.04 investigation is done, so let's close this story.
