### ISSUE TITLE
Investigate RHEL8(phase1)

### ISSUE THREAD

**Issue by neo954** [xcat2/xcat2-task-management#196]
* [x] pkglist, template need to be updated
* [x] Open issues for RHEL8 support (in 2.14.2 sprint 2)
* [ ] Fix issues (may move to 2.14.3)

**Comment by zet809** [comment]
The investigation done, let's close this task
