### ISSUE TITLE
Investigate confluent discover + hw_ctrl on IPV6

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat2-task-management#197]
* [x] confluent document verification
* [x] document about the logic
* [x] how to support in xCAT

**Comment by xuweibj** [comment]
How to support in xCAT
* discover:
In confluent, use slp protocol to get bmc/node information.
In xCAT, there is ``lsslp`` command to get information by slp.
```
(type=integrated-management-module2),(level=4),(server-type=Processor Blade),(enclosure-function=server),(enclosure-form-factor=BC2),(name=c910f05c01bc08 ),(hostname=IMM2-3440b5bf4d5d),(ipv4-address=50.5.1.108),(ipv6-addresses=fd8c:215d:178e:c0de:3640:b5ff:febf:4d5d,fe80::3640:b5ff:febf:4d5d,fe80::3640:b5ff:febf:4d5c),(mac-address=34:40:b5:bf:4d:5d,34:40:b5:bf:4d:5c),(usb-ip-address=169.254.95.118),(usb-mac-address=34:40:b5:bf:4d:5e),(enclosure-serial-number=1033F2B),(enclosure-fru=81Y5128     ),(enclosure-machinetype-model=786310X),(node-uuid=\FF\70\1B\90\94\E7\F2\11\E1\A2\B3\34\40\B5\BE\7C\D8),(location=location),(room-id=),(rack-id=),(lowest-u=),(u-height=),(slot=8),(blade-type=0220),(mid-pid=00004f4d\2c0141),(ipv4-enabled=true),(ipv4-protocols=cimxml-http:5988:true,cimxml-https:5989:true,http:80:true,https:443:true,snmpv1:161:true,snmpv3:161:true,ssh:22:true,rem-pres:3900:true,rmcp:623:true),(ipv6-enabled=true),(ipv6-protocols=cimxml-http:5988:true,cimxml-https:5989:true,http:80:true,https:443:true,snmpv1:161:true,snmpv3:161:true,ssh:22:true,rem-pres:3900:true,rmcp:623:true,cmm-mgmt:703:true),(firmware-image-info=1AOO40E:2.00:2013/01/14,B2E122DUS:1.21:2013/03/28),(scalable=0),(mn-node-number=0),(enclosure-uuid=\FF\70\1B\90\94\E7\F2\11\E1\A2\B3\34\40\B5\BE\7C\D8),(chassis-machinetype-model=789392X),(chassis-serial-number=10045CA),(chassis-uuid=\FF\67\6B\B2\AE\B8\63\4A\DB\81\03\63\96\4D\31\07\F4),(all-slots=8),(half-width=1),(ssh-fingerprint=9e:73:2c:fa:ee:05:56:bf:51:5d:98:23:cc:71:3f:af),(snmp-engine-id=\FF\80\00\1F\88\80\F3\8D\99\1F\94\85\EB\58),(secure-indication=true)
```
But maybe will get 2 IPv6 addresses.
To make suer which IPv6 address is connected, could check which is pingable by bmc connected nic.

* hw ctrl: (ipmi)
It seems that IPMI protocol support IPv6.
Design bmc as IPv4 and IPv6, if failed when use IPv4, use IPv6 try again.

**Comment by zet809** [comment]
To discovery openbmc with slp, openbmc support unicast messages,don't support discovery through multicast SLP.
As we want to get MTMS also for OpenBMCs, so, maybe not so valuable at present(We have bmcdiscovery to discover openBMC through RESTful interface). So, let me close this task.

```
[root@briggs01 tmp]# slptool -u 172.11.139.16 findsrvtypes
service:obmc_console
service:phosphor_rest
service:sftp
service:ssh
[root@briggs01 tmp]# slptool -u 172.11.139.16 findsrvs service:obmc_console
service:obmc_console:tcp//169.254.55.91,2200,5
service:obmc_console:tcp//169.254.254.244,2200,5
service:obmc_console:tcp//172.11.139.16,2200,5
[root@briggs01 tmp]# slptool -u 172.11.139.16 findsrvs service:phosphor_rest
service:phosphor_rest:tcp//169.254.55.91,443,5
service:phosphor_rest:tcp//169.254.254.244,443,5
service:phosphor_rest:tcp//172.11.139.16,443,5
[root@briggs01 tmp]# slptool -u 172.11.139.16 findsrvs service:ssh
service:ssh:tcp//169.254.55.91,22,5
service:ssh:tcp//169.254.254.244,22,5
service:ssh:tcp//172.11.139.16,22,5
```
