### ISSUE TITLE
Build framework enhancements

### ISSUE THREAD

**Issue by xuweibj** [xcat2/xcat2-task-management#253]
* [x] setup docker host ==> Jenkins slave        ==>1 point
    * [x] OS + docker enginer + docker image + mount FS + xcat key + step by step
* [x] Setup a whole build environment, could build xcat-core tarball directly ==> 2 points
    * [x] setup jenkins master
    * [x] add slave in master
    * [x] trigger docker run to build xcat-core
    * [x] return URL about the build
    * [x] others
* [ ] Support other operations by python scripts investigate ==> 2 points
    * [x] multiple user
    * [ ] del, list...
* [ ] Setup build framework for daily build  ---- investigation done
    * [x] setup daily build project on jenkins
    * [x] token for clone daily build python script -> use ssh key 
    * [x] gpg key on slave
    * [x] cli to trigger daily build with user check
    * [x] upload build to one node

**Comment by zet809** [comment]
Use this EPIC to replace #233.

**Comment by xuweibj** [comment]
Close it first, will open new task for ``del, list`` operations.
