### ISSUE TITLE
build and test scripts to for xcat-docker

### ISSUE THREAD

**Issue by robin2008** [xcat2/xcat2-task-management#508]
This story cover below:
- [x] makefile or build script to auto build the containers and publish ==> 1.5
- [x] enhance current jenkintest script to support using container for regression testing. (https://github.com/xcat2/xcat2-task-management/issues/530)
- [x] workout the test buckets which available for xcat container ==>1
- [x] test driven for container based xcat regression testing ==> 2

**Comment by robin2008** [comment]
close this EPIC as all thing done in https://github.ibm.com/xcat2/task_management/issues/60
