### ISSUE TITLE
[xcat-devops]offline repos for ML/DL/APP users

### ISSUE THREAD

**Issue by zet809** [xcat2/xcat2-task-management#511]
Scenario: As ML/DL/APP user, after download 3-rd party packages, need to setup offline repo easily.

* [x] leverage Ansible playbook/modules to automate repo setup: https://github.com/xcat2/xcat2-task-management/issues/569
    
* [x] repos ==>
  * [x] os+epel+conda: https://github.com/xcat2/xcat2-task-management/issues/512
  * [x] 3rd party, GPU related+poweai+dli: https://github.com/xcat2/xcat2-task-management/issues/548

~~compare our solution with POWERUP: https://power-up.readthedocs.io/en/latest/Running-paie.html#running-paie~~

~~scripts to check the generated offline repo~~

**Comment by zet809** [comment]
Playbooks: https://ansible-tran.readthedocs.io/en/latest/docs/playbooks_intro.html
Ansible: https://ansible-tran.readthedocs.io/en/latest/docs/intro_adhoc.html
