### ISSUE TITLE
[RH8] Make confignetwork vlan/bond/bridge work on RHEL 8

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat2-task-management#572]
In RH8, NetworkManager is used to config network, so the following function shall based on NetworkManager 
* [x] confignetwork framework refine to support NetworkManager
* [x] confignetwork framework mini-design
* [x] investigate the nmcli interface differences among ubuntu, sles and redhat
* [x] configure tagged vlan -- v2
* [x] configure  link aggregation -- config bond v2
* [x] configure bridge -- v2
