### ISSUE TITLE
[IaC] investigate K8s to burst pods/services to xCAT Cluster with K8s/Cluster Autoscaler

### ISSUE THREAD

**Issue by immarvin** [xcat2/xcat2-task-management#592]
[K8s/Cluster Autoscaler](https://github.com/kubernetes/autoscaler), abbrev to **CA**, is a component that automatically adjusts the size of a Kubernetes Cluster so that all pods have a place to run and there are no unneeded nodes. This task is to investigate the prospect and feasibility on how to enable K8s burst pods/services to xCAT Cluster with K8s/Cluster Autoscaler.

The output of the this epic should include:

* [x] a introduction include the information: "what is K8s/autoscaler?", "how does K8s/autoscaler work?" 
* [x] a design to answer the questions: "what is the value of this work?" and "what is the position of xCAT/xcat-inventory in K8s/autoscaler?" 
* [x] initiate a discussion based on the design, obtain a agreement on whether to implementation 
* [x] obtain the information on "how to create a  xCAT provider for K8s/autoscaler"
* [x] check whether  there is any project to enable autoscaler to invoke Terraform, asked in https://github.com/kubernetes/autoscaler/issues/1619 
* [x] check with ICP team on "How ICP achieve autoscale?"
~~[ ] test cases~~
~~[ ] implement the xCAT CA provider~~
