### ISSUE TITLE
Function verification test against xCAT RHEL 8 support

### ISSUE THREAD

**Issue by hu-weihua** [xcat2/xcat2-task-management#620]
what to do:

Do rhels8.0 new os support test 

* [ ] build  ``xcat-core`` through ``git@github.com:xcat2/xcat-core.git`` & ``rhels8`` branch.

* [ ] Do regression , check if it affect original supporting os(rhels6.10 rhels 7.6 pegas 1.2  ubuntu 16.4.5 ubuntu 18.4.1 sles 12.3 sles 11.4),
    ```
        xcat-core : above package
        xcat-dep linux:  http://xcat.org/files/xcat/xcat-dep/2.x_Linux/xcat-dep-201811190436.tar.bz2
        xcat-dep debain:  http://xcat.org/files/xcat/xcat-dep/2.x_Ubuntu/xcat-dep-ubuntu-201811200025.tar.bz2
    ```
* [ ] Depending on [New OS Support Checklist](https://w3-connections.ibm.com/wikis/home?lang=en#!/wiki/xCAT/page/New%20OS%20Support%20Checklist%20Template) to do verify for rhels8.0. 
    ```
        xcat-core : above package
        xcat-dep linux:  download from https://github.com/xcat2/xcat2-task-management/issues/443
    ```

**Comment by neo954** [comment]
@hu-weihua, Please do not get `xcat-core` tarball from epic #443. You should create build from the `rhels8` branch of `git@github.com:xcat2/xcat-core.git` repository.

**Comment by hu-weihua** [comment]
Close this epic. will be replaced by epic #622 and #627
