### ISSUE TITLE
confignetwork advanced feature support using nmcli

### ISSUE THREAD

**Issue by bybai** [xcat2/xcat2-task-management#653]
confignetwork advanced feature support using nmcli

* [ ] confignetwork support "-r" action (https://github.com/xcat2/xcat-core/issues/6142)
* [ ] investigate and enhance configib to support NetworkManager (https://github.com/xcat2/xcat2-task-management/issues/651, https://github.com/xcat2/xcat2-task-management/issues/652)
* [ ] confignetwork support nicextraparams using nmcli (https://github.com/xcat2/xcat2-task-management/issues/650)
* [ ] confignetwork fails to config second iP for one nic on rhels8 (https://github.com/xcat2/xcat-core/issues/6135)
* [ ] If set CN installation nic with static ip, the hostname of CN will be localhost, not node name (https://github.com/xcat2/xcat-core/issues/6088)

**Comment by bybai** [comment]
This EPIC is moved into HPC-xCAT, close this EPIC.
